github:
  is_project_page: false
description:
show_downloads: false
name: null
title: Artificial Intelligence and Machine Learning with Python
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
